"""
Django settings for askdjango project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from os.path import abspath, dirname, join
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# 장고 프로젝트 ROOT경로를 계산 settings.py의 위치를 기준으로 계산
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) # abspath,dirname,join 임포트
# ROOT 경로는 src
# /Users/giyeon/01Nomade/05django/01firstvod/src/askdjango/settings.py 변경전
# /Users/giyeon/01Nomade/05django/01firstvod/src/askdjango/settings/common.py 변경후
BASE_DIR = dirname(dirname(dirname(abspath(__file__))))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', #장고 기본디렉토리 앱 6가지
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites', #페이스북/카카오/네이버로그인, Migrate해줘야함
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.kakao',
    'allauth.socialaccount.providers.naver',

    'bootstrap3',
    
    'django_extensions',
    'imagekit', #image thumbnail
    'raven.contrib.django.raven_compat', #Sentry를 통한 에러로깅
    'accounts',
    'blog', #생성한 앱 등록 필수!!
    'dojo',
    'shop',
]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'askdjango.urls' #최상위 urlconf로 정한다.

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ # filesystem.Loader
            os.path.join(BASE_DIR, 'askdjango', 'templates'),
        ],
        'APP_DIRS': True, #등록된 앱  app_directories.Loader
        'OPTIONS': {
            'context_processors': [ 
            # 템플릿을 렌더링 할때 인자로 직접 넘겨주지 않았도, 
            # 컨텍스 프로세서에 지정되어있는 함수들은 매번 테플릿 렌더링 하기 직전에 호출해서, 
            # 함수들이 리턴한 사전의 값들을 다 합쳐서 그 값들을 템플릿에 전달 
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth', #뷰에서 구현하지 않아도 템플릿에서 호출가능
                'django.contrib.messages.context_processors.messages',
                #커스텀
                'blog.context_processors.blog',
            ],
        },
    },
]

WSGI_APPLICATION = 'askdjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
 'django.contrib.auth.backends.ModelBackend', # 기본 인증 백엔드
 'allauth.account.auth_backends.AuthenticationBackend', # 추가 
]

SITE_ID = 1

SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



#STATIC은 개발 리소스로써의 정적인 파일
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/' #개발 리소스로서의 정적파일을 서빙, 각 static 파일에 대한 URL Prefix, view url처럼
STATICFILES_DIRS=[ 
    os.path.join(BASE_DIR, 'askdjango','static'),
] 
#FileSystemFinder를 위한 static 디렉토리 목록, 프로젝트 전반적으로 사용될 static파일의 디렉토리 경로를 다수지정
#1)앱 디렉토리 파인더 : 기본활성화
#2)파일시스템 파인더 : STATICFILES_DIRS로 이 경로에 정적인 파일이 있음을 알려준다.

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#python manage.py collectstatic으로 폴더생성 및 흩어진 static을 복사해서 모아줌(절대경로)
#프로젝트/urls.py에 지정도 안해줬는데 어떻게 응답처리?
#개발환경에서의 static파일 서빙 지원(when, DEBUG=True)
#개발목적!으로만 제공(python manage.py runserver)


#MEDIA는 유저가 업로드한 모든 파일
MEDIA_URL= '/media/' #유저가 업로드한 파일을 서빙할 때, prefix url, 끝이 필히 /로 끝나야함
MEDIA_ROOT= os.path.join(BASE_DIR, 'media')  #유저가 업로드한 파일을 저장하는 ROOT경로(절대경로)
#STATIC files와 다르게 개발서버에서 서빙 미지원
#개발 편의성 목적으로 직접 서빙 Rule추가 가능!
#이렇게 하더라도 DEBUG=False일때는 static함수에서 빈 리스트를 리턴


# NOTEBOOK_KERNEL_SPEC_NAMES = ['Python [Root]'] #일반 shell에서 django로 접근하는방법
'''
import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myproj.settings') # FIXME: 경로 확인
import django
django.setup()
# 지금부터 모든 장고환경에 접근 가능
from blog.models import Post
일반 쉘에서도 장고 환경에 접근은 가능하나
django shell을 쓰는 것이 편리
'''



from django.contrib.messages import constants

MESSAGE_LEVEL = constants.DEBUG #지금부터 debug레벨의 messages를 남길 수 있음..
MESSAGE_TAGS ={constants.ERROR: 'danger'}

NAVER_CLIENT_ID = 'JCv1RVmz_rGXNeiCaFMT'


import raven
GIT_ROOT = BASE_DIR # FIXME: 현 프로젝트 ROOT 지정
if os.path.exists(os.path.join(GIT_ROOT, '.git')):
    release = raven.fetch_git_sha(GIT_ROOT) # 현재 최근 커밋해시 획득
else:
    release = 'dev'

RAVEN_CONFIG = {
    'dsn': 'https://0b4cb1fb89b345e39f748e66b411ab80:d1fa6f82f5e741dfb9aa0deaacc27cd5@sentry.io/243855',
    # If you are using git, you can also automatically configure the
    # release based on the git info.
    'release': release,
}

