# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-07 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0003_auto_20171107_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='server_name',
            field=models.CharField(choices=[('A', 'A서버'), ('B', 'B서버'), ('C', 'C서버')], max_length=10),
        ),
    ]
